export { default as BaseBody} from './BaseBody'
export { default as BaseComponent } from './BaseComponent'
export { default as GuestComponent } from './GuestComponent' 
export { default as UserHeader } from './UserHeader' 
export { default as BaseFooter } from './BaseFooter' 